# Generated by Django 3.2.2 on 2021-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='answered_calls',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calls',
            name='incoming_calls',
            field=models.IntegerField(null=True),
        ),
    ]
