# Generated by Django 3.2.2 on 2021-05-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210515_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='month',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='calls',
            name='year',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
