# Generated by Django 3.2.2 on 2021-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210515_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='departament',
            field=models.CharField(blank=True, default='1111', max_length=128),
        ),
        migrations.AlterField(
            model_name='calls',
            name='month',
            field=models.CharField(blank=True, default='1111', max_length=32),
        ),
        migrations.AlterField(
            model_name='calls',
            name='year',
            field=models.CharField(blank=True, default='1111', max_length=32),
        ),
    ]
