# Generated by Django 3.2.2 on 2021-05-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210515_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='cc_monthly_st',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('departament', models.CharField(blank=True, default='1111', max_length=128)),
                ('incoming_calls', models.IntegerField(null=True)),
                ('answered_calls', models.IntegerField(null=True)),
                ('month', models.CharField(blank=True, default='1111', max_length=32)),
                ('year', models.CharField(blank=True, default='1111', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Calls',
            },
        ),
        migrations.DeleteModel(
            name='calls',
        ),
    ]
