# Generated by Django 3.2.2 on 2021-05-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210516_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cc_monthly_st',
            old_name='incoming_calls',
            new_name='total_calls',
        ),
        migrations.AlterField(
            model_name='cc_monthly_st',
            name='departament',
            field=models.CharField(blank=True, default='nul', max_length=128),
        ),
        migrations.AlterField(
            model_name='cc_monthly_st',
            name='month',
            field=models.CharField(blank=True, default='nul', max_length=32),
        ),
        migrations.AlterField(
            model_name='cc_monthly_st',
            name='year',
            field=models.CharField(blank=True, default='nul', max_length=32),
        ),
    ]
