# Generated by Django 3.2.2 on 2021-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20210516_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='cc_monthly_st',
            name='abandonment_rate',
            field=models.CharField(blank=True, default='null', max_length=32),
        ),
        migrations.AddField(
            model_name='cc_monthly_st',
            name='response_time',
            field=models.CharField(blank=True, default='null', max_length=32),
        ),
        migrations.AddField(
            model_name='cc_monthly_st',
            name='service_level',
            field=models.CharField(blank=True, default='null', max_length=32),
        ),
        migrations.AlterField(
            model_name='cc_monthly_st',
            name='departament',
            field=models.CharField(blank=True, default='null', max_length=128),
        ),
        migrations.AlterField(
            model_name='cc_monthly_st',
            name='month',
            field=models.CharField(blank=True, default='null', max_length=32),
        ),
        migrations.AlterField(
            model_name='cc_monthly_st',
            name='year',
            field=models.CharField(blank=True, default='null', max_length=32),
        ),
    ]
