# Generated by Django 3.2.2 on 2021-05-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('recid', models.AutoField(primary_key=True, serialize=False)),
                ('calldate', models.DateTimeField()),
                ('clid', models.CharField(max_length=80)),
                ('src', models.CharField(max_length=80)),
                ('dst', models.CharField(max_length=80)),
                ('dcontext', models.CharField(max_length=80)),
                ('channel', models.CharField(max_length=80)),
                ('dstchannel', models.CharField(max_length=80)),
                ('lastapp', models.CharField(max_length=80)),
                ('lastdata', models.CharField(max_length=80)),
                ('duration', models.IntegerField()),
                ('billsec', models.IntegerField()),
                ('disposition', models.CharField(max_length=45)),
                ('amaflags', models.IntegerField()),
                ('accountcode', models.CharField(max_length=20)),
                ('uniqueid', models.CharField(max_length=32)),
                ('userfield', models.CharField(max_length=255)),
                ('linkedid', models.CharField(max_length=32)),
                ('destination', models.CharField(max_length=45)),
                ('user_id', models.CharField(max_length=45)),
                ('listen', models.IntegerField()),
                ('reported', models.IntegerField()),
                ('trunk', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cdr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=32, null=True)),
                ('callid', models.CharField(blank=True, max_length=64, null=True)),
                ('queuename', models.CharField(blank=True, max_length=64, null=True)),
                ('uniqueid', models.CharField(max_length=45)),
                ('agent', models.CharField(blank=True, max_length=64, null=True)),
                ('event', models.CharField(blank=True, max_length=32, null=True)),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
                ('data1', models.CharField(blank=True, max_length=64, null=True)),
                ('data2', models.CharField(blank=True, max_length=64, null=True)),
                ('data3', models.CharField(blank=True, max_length=64, null=True)),
                ('data4', models.CharField(blank=True, max_length=64, null=True)),
                ('data5', models.CharField(blank=True, max_length=64, null=True)),
                ('rating', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'queue_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('exten', models.CharField(blank=True, max_length=16, null=True)),
                ('state', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'statelog',
                'managed': False,
            },
        ),
    ]
